USE [master]
GO

/****** Object:  Database [Lakaszovetkezet]    Script Date: 2017. 01. 24. 8:10:58 ******/
CREATE DATABASE [Lakaszovetkezet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lakaszovetkezet', FILENAME = N'C:\Users\inch\Lakaszovetkezet.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Lakaszovetkezet_log', FILENAME = N'C:\Users\inch\Lakaszovetkezet_log.ldf' , SIZE = 560KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Lakaszovetkezet] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lakaszovetkezet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lakaszovetkezet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Lakaszovetkezet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lakaszovetkezet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lakaszovetkezet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Lakaszovetkezet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lakaszovetkezet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Lakaszovetkezet] SET  MULTI_USER 
GO

ALTER DATABASE [Lakaszovetkezet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lakaszovetkezet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lakaszovetkezet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lakaszovetkezet] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Lakaszovetkezet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lakaszovetkezet] SET  READ_WRITE 
GO


